version: "3"
services:
  text-generation-webui-docker:
    build:
      context: .
      target: default  # Specify the variant to build
      args:
        - VERSION_TAG="v1.6"  # Checkout this specific tag from upstream. Omit or set `nightly` for latest.
#        - BUILD_DATE="1970-01-01"  # Set the build date as desired
#        - LCL_SRC_DIR=text-generation-webui  # Developers - see Dockerfile app_base
    container_name: text-generation-webui
    environment:
      - EXTRA_LAUNCH_ARGS="--loader exllamav2 --alpha 2.7 --max_seq_len 8192 --api --listen --api-blocking-port 5000 --api-streaming-port 5001 --model Redwood0_Iambe-Storyteller-20b-4.65bpw-h8-exl2" # Custom launch args (e.g., --model MODEL_NAME)
#      - BUILD_EXTENSIONS_LIVE="silero_tts whisper_stt" # Install named extensions during every container launch. THIS WILL SIGNIFICANLTLY SLOW LAUNCH TIME.
    ports:
      - 7860:7860  # Default web port
      - 5000:5000  # Default API port
      - 5001:5001  # Default streaming port
      - 6000:6000  # Default OpenAI API extension port
    volumes:
      - ./config/characters:/app/characters
      - ./config/loras:/app/loras
      - ./config/models:/app/models
      - ./config/presets:/app/presets
      - ./config/prompts:/app/prompts
      - ./config/training:/app/training
      - ./config/extensions:/app/extensions  # Persist all extensions
#      - ./config/extensions/silero_tts:/app/extensions/silero_tts  # Persist a single extension
    logging:
      driver:  json-file
      options:
        max-file: "3"   # number of files or file count
        max-size: '10m'
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]
